# Generated by Django 4.2.5 on 2023-10-05 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('I', 'Exam of image'), ('B', 'Exam of blood')], max_length=1)),
                ('price', models.FloatField()),
                ('available', models.BooleanField(default=True)),
                ('hour_init', models.IntegerField()),
                ('hour_final', models.IntegerField()),
            ],
        ),
    ]
