# Generated by Django 4.2.5 on 2023-10-05 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSolicitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('W', 'Waiting'), ('U', 'Under review'), ('F', 'Finalized')], max_length=2)),
                ('result', models.FileField(blank=True, null=True, upload_to='results')),
                ('requires_password', models.BooleanField(default=False)),
                ('password', models.CharField(blank=True, max_length=10, null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='exams.examstype')),
            ],
        ),
    ]
