# Generated by Django 4.2.5 on 2023-10-05 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0003_examsolicitation_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled', models.BooleanField(default=True)),
                ('data', models.DateField()),
                ('exams', models.ManyToManyField(to='exams.examsolicitation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
